### ISSUE TITLE
don't require user-implemented `isDirty` function on the datamodel

### ISSUE THREAD

**Issue by joechrz** [gridgrid/grid#19]
```
// use the grid's default dirty clean implementation almost always
// (it will automatically be set clean on each draw by the grid)
```

might as well just do this internally... I forget it every time.

**Comment by scamden** [comment]
well you would still have to call set dirty on it.. would love to hear more how you would want this to work

**Comment by scamden** [comment]
default data model allows the user not to make their own closing in favor of that
