### ISSUE TITLE
Bundling with webpack

### ISSUE THREAD

**Issue by alexkrolick** [gridgrid/grid#36]
Is it currently feasible to import `grid` into a Webpack/React project?

**Comment by scamden** [comment]
It is! It’s in earlyish stages using a beta v4 version of the grid but
check out grid-react-adapter. No docs yet so feel free to ping me with
questions!

**Comment by scamden** [comment]
On a side not this project can be imported directly and bundled with webpack. The react adapter just exposes a component to help make the react bindings since this is written in pure js in a more imperative style.
